<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
    <Page Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
    <Page Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="9.6.0" />
    <PackageReference Include="LLamaSharp" Version="0.20.0" />
    <PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.20.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.7" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.DirectML" Version="0.13.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Managed" Version="0.13.2" />
    <PackageReference Include="QuestPDF" Version="2026.2.4" />
    <PackageReference Include="System.Text.Json" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\GoogleModelSelectionDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\GoogleModelSelectionDialog.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>